import React from "react";

import { RiFileCopy2Line } from "react-icons/ri";
import { FiPaperclip } from "react-icons/fi";
import { LuTimer } from "react-icons/lu";
import { RiHeart2Line } from "react-icons/ri";

import HomeImg from "../assets/talent-forge-01.png";
import AboutImg from "../assets/talent-forge02.jpg";


//Import swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";

// import required modules

import { Autoplay } from "swiper/modules";

const Model = () => {
  return (
    <div className="container">
      <Swiper
        slidesPerView={2}
        spaceBetween={20}
        autoplay={{
          delay: 2000,
          disableOnInteraction: false,
        }}
        breakpoints={{
          640: {
            slidesPerView: 1,
            spaceBetween: 20,
          },
          768: {
            slidesPerView: 3,
            spaceBetween: 40,
          },
          1024: {
            slidesPerView: 3,
            spaceBetween: 50,
          },
        }}
        modules={[Autoplay]}
        className="mySwiper"
      >
        <SwiperSlide>
          <div className=" bg-secondaryg sponsor-item col-12 d-flex flex-column align-items-center justify-content-center">
            <div className="sponsor-thumb bg-primary d-flex p-3 justify-content-center align-items-center">
              <RiFileCopy2Line className="sponsor-icon" />
            </div>
            <h6 className="sponsor--txt fw-bold">Recruitment Fee</h6>
            <p className="sponsor-desc text-center">
              Revenue is generated by charging organizations a fee for
              successful candidate placements
            </p>
          </div>
        </SwiperSlide>
      </Swiper>
    </div>
  );
};

export default Model;
