import React from "react";

import { RiFileCopy2Line } from "react-icons/ri";
import { FiPaperclip } from "react-icons/fi";
import { LuTimer } from "react-icons/lu";
import { RiHeart2Line } from "react-icons/ri";

//Import swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";

// import required modules

import { Autoplay } from "swiper/modules";

const Model = () => {
  return (
    <div className="container mt-5" id="model">
      <div className="head--sec d-flex justify-content-center shadow-sm">
        <h1 className="fw-bold head-txt fs-1">BUSINESS MODEL</h1>
      </div>
      <Swiper
        slidesPerView={2}
        spaceBetween={20}
        autoplay={{
          delay: 2000,
          disableOnInteraction: false,
        }}
        breakpoints={{
          380: {
            slidesPerView: 1,
            spaceBetween: 90,
          },
          768: {
            slidesPerView: 2,
            spaceBetween: 40,
          },
          1024: {
            slidesPerView: 3,
            spaceBetween: 50,
          },
        }}
        modules={[Autoplay]}
        className="mySwiper p-5"
      >
        <SwiperSlide>
          <div className="sponsor-item p-4 col-12 d-flex flex-column align-items-center justify-content-center shadow-lg card">
            <div className="sponsor-thumb bg-primary d-flex p-3 justify-content-center align-items-center mb-3">
              <RiFileCopy2Line className="sponsor-icon" />
            </div>
            <h6 className="sponsor--txt fw-bold mb-3">Recruitment Fee</h6>
            <p className="sponsor-desc text-center col-11 col-sm-9 ">
              Revenue is generated by charging organizations a fee for
              successful candidate placements
            </p>
          </div>
        </SwiperSlide>
        <SwiperSlide>
          <div className="sponsor-item p-4 col-12 d-flex flex-column align-items-center justify-content-center shadow-lg card">
            <div className="sponsor-thumb bg-success-subtle d-flex p-3 justify-content-center align-items-center mb-3">
              <FiPaperclip className="sponsor-icon" />
            </div>
            <h6 className="sponsor--txt fw-bold mb-3">Outsourcing Fee</h6>
            <p className="sponsor-desc text-center col-11 col-sm-9 ">
              Talent Forge generates revenue when clients pay for outsourced
              tasks or functions
            </p>
          </div>
        </SwiperSlide>
        <SwiperSlide>
          <div className="sponsor-item p-4 col-12 d-flex flex-column align-items-center justify-content-center shadow-lg card">
            <div className="sponsor-thumb bg-primary d-flex p-3 justify-content-center align-items-center mb-3">
              <LuTimer className="sponsor-icon" />
            </div>
            <h6 className="sponsor--txt fw-bold mb-3">Fee for Trainings</h6>
            <p className="sponsor-desc text-center col-12 col-sm-9 ">
              Revenue through trainings and workshops, charging organizations or
              individuals for participation
            </p>
          </div>
        </SwiperSlide>
        <SwiperSlide>
          <div className="sponsor-item p-4 col-12 d-flex flex-column align-items-center justify-content-center shadow-lg card">
            <div className="sponsor-thumb bg-success-subtle d-flex p-3 justify-content-center align-items-center mb-3">
              <RiHeart2Line className="sponsor-icon" />
            </div>
            <h6 className="sponsor--txt fw-bold mb-3">
              Consulting Retainer Fee
            </h6>
            <p className="sponsor-desc text-center col-11 col-sm-9 ">
              Clients pay a quarterly retainer fee for ongoing consulting or
              advisory service.
            </p>
          </div>
        </SwiperSlide>
      </Swiper>
    </div>
  );
};

export default Model;
